export var ContactData = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Contact',
    headLine: 'Contact Us Here',
    description: 'Contact us if you have any questions or comments. We will get back to you as soon as possible.',
    includeBtn: true,
    buttonLabel: 'Contact Us',
    videoThmbn: true,
    img:'',
    alt: '',
    dark: true,
    primary: true,
    darkText: true,
}