export var homeObjOne = {
    
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headLine: 'What Is Save4Me?',
    description: 'Save4Me is a universal media downloading service that offers audio (MP3) and video (MP4) formats for download configurations. Save4Me offers all available resolution qualities from 144p to 1080p. Save4Me is a free service that is available to all users. Save4Me is a free service that is available to all users and supported on all platforms.',
    includeBtn: false,
    buttonLabel: '',
    videoThmbn: true,
    img: '',
    alt: '',
    dark: true,
    primary: true,
    darkText: false,
}

export var homeObjTwo = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Contact',
    headLine: 'You Can Contact Us Here',
    description: 'Lorem ipsum dolor sit amet, Excepteur sint occaecat cupidatat non proident. Lorem ipsum dolor sit amet',
    includeBtn: true,
    buttonLabel: 'Contact Us',
    videoThmbn: false,
    img:'',
    alt: '',
    dark: true,
    primary: true,
    darkText: true,
}